import {
  AmazonLogo,
  AmazonSageMakerLogo,
  AnalyticsLogo,
  AnsibleLogo,
  ApacheFlinkLogo,
  AwsDynamodbLogo,
  AzureLogo,
  CassandraLogo,
  ChefLogo,
  ClientImg,
  CloudSpannerLogo,
  CockroachLogo,
  CouchbaseLogo,
  CplusplusLogo,
  CsSarpLogo,
  DartLogo,
  DigitalLogo,
  DockerLogo,
  ElasticLogo,
  GitHubActionsLogo,
  GitlabLogo,
  GoLogo,
  GoogleAiLogo,
  GooglecloudLogo,
  HadoopLogo,
  HemlLogo,
  HuggingFaceLogo,
  IbmCloudLogo,
  IconsServicesLogo,
  JavaLogo,
  JavascriptLogo,
  JenkinsLogo,
  KafkaLogo,
  KerasLogo,
  KotlinLogo,
  KubernetsLogo,
  LookerSvgrepoLogo,
  MemSQLLogo,
  MicrosoftSqlLogo,
  MongoDBLogo,
  MysqlLogo,
  NLTKLogo,
  OpenAiLogo,
  OpenShiftLogo,
  OracleDataCloudLogo,
  OracleLogo,
  PhpLogo,
  PostgresqlLogo,
  PowerLogo,
  PuppetLogo,
  PythonLogo,
  PytorchLogo,
  QlikLogo,
  RedisLogo,
  RLogo,
  RubyLogo,
  RustLogo,
  SLearnLogo,
  SpaCyLogo,
  SparkSvgrepoLogo,
  SqliteLogo,
  SwiftLogo,
  TableauSvgrepoLogo,
  TechLogo,
  TensorFlowLogo,
  TerraformLogo,
  TravisLogo,
  TypescriptLogo,
  VoltDBLogo,
  XGBoostLogo,
} from "@/images";

import {
  globeIcon,
  rocketIcon,
  SettingIcon,
  toolIcon,
  MoneyBagIcon,
  EarthWithStandIcon,
  PointerArrow,
  FacebookIcon,
  TwitterIcon,
  InstagramIcon,
  LinkdinIcon,
  YoutubeIcon,
} from "@/components/Icons";

export const titleData = [
  { id: 1, title: "Tools & Programming Languages" },
  { id: 2, title: "Cloud Computing & DevOps" },
  { id: 3, title: "Databases" },
  { id: 4, title: "Big Data & Analytics" },
  { id: 5, title: "Machine Learning & AI" },
];

export const languagesIconData = [
  [
    { id: 1, logo: PythonLogo, alt: "python-logo" },
    { id: 2, logo: RustLogo, alt: "rust-logo" },
    { id: 3, logo: JavascriptLogo, alt: "javascript-logo" },
    { id: 4, logo: TypescriptLogo, alt: "typescript-logo" },
    { id: 5, logo: CsSarpLogo, alt: "c-sarp-logo" },
    { id: 6, logo: CplusplusLogo, alt: "c-plus-logo" },
    { id: 7, logo: RubyLogo, alt: "ruby-logo" },
    { id: 8, logo: GoLogo, alt: "go-logo" },
    { id: 9, logo: RLogo, alt: "r-logo" },
    { id: 10, logo: JavaLogo, alt: "java-logo" },
    { id: 11, logo: DartLogo, alt: "dart-logo" },
    { id: 12, logo: PhpLogo, alt: "php-logo" },
    { id: 13, logo: SwiftLogo, alt: "swift-logo" },
    { id: 14, logo: KotlinLogo, alt: "kotlin-logo" },
  ],
  [
    { id: 1, logo: AzureLogo, alt: "Azure-logo" },
    { id: 2, logo: KubernetsLogo, alt: "Kubernets-logo" },
    { id: 3, logo: GooglecloudLogo, alt: "Googlecloud-logo" },
    { id: 4, logo: AmazonLogo, alt: "Amazon-logo" },
    { id: 5, logo: GitlabLogo, alt: "Gitlab-logo" },
    { id: 6, logo: HemlLogo, alt: "Heml-logo" },
    { id: 7, logo: AnsibleLogo, alt: "Ansible-logo" },
    { id: 8, logo: IbmCloudLogo, alt: "IbmCloud-logo" },
    { id: 9, logo: TravisLogo, alt: "Travis-logo" },
    { id: 10, logo: PuppetLogo, alt: "Puppet-logo" },
    { id: 11, logo: JenkinsLogo, alt: "Jenkins-logo" },
    { id: 12, logo: OpenShiftLogo, alt: "OpenShift-logo" },
    { id: 13, logo: DockerLogo, alt: "Docker-logo" },
    { id: 14, logo: OracleDataCloudLogo, alt: "OracleDataCloud-logo" },
    { id: 15, logo: ChefLogo, alt: "Chef-logo" },
    { id: 16, logo: GitHubActionsLogo, alt: "GitHubActions-logo" },
    { id: 17, logo: TerraformLogo, alt: "Terraform-logo" }
  ],
  [
    { id: 1, logo: MysqlLogo, alt: "Mysql-logo" },
    { id: 2, logo: PostgresqlLogo, alt: "Postgresql-logo" },
    { id: 3, logo: SqliteLogo, alt: "Sqlite-logo" },
    { id: 4, logo: OracleLogo, alt: "Oracle-logo" },
    { id: 5, logo: MicrosoftSqlLogo, alt: "MicrosoftSql-logo" },
    { id: 6, logo: MongoDBLogo, alt: "MongoDB-logo" },
    { id: 7, logo: CloudSpannerLogo, alt: "CloudSpanner-logo" },
    { id: 8, logo: CouchbaseLogo, alt: "Couchbase-logo" },
    { id: 9, logo: RedisLogo, alt: "Redis-logo" },
    { id: 10, logo: ElasticLogo, alt: "Elastic-logo" },
    { id: 11, logo: AwsDynamodbLogo, alt: "AwsDynamodb-logo" },
    { id: 12, logo: CockroachLogo, alt: "Cockroach-logo" },
    { id: 13, logo: CassandraLogo, alt: "Cassandra-logo" },
    { id: 14, logo: MemSQLLogo, alt: "MemSQL-logo" },
    { id: 15, logo: VoltDBLogo, alt: "VoltDB-logo" },
  ],
  [
    { id: 1, logo: KafkaLogo, alt: "Kafka-logo" },
    { id: 2, logo: HadoopLogo, alt: "Hadoop-logo" },
    { id: 3, logo: SparkSvgrepoLogo, alt: "SparkSvgrepo-logo" },
    { id: 4, logo: ApacheFlinkLogo, alt: "ApacheFlink-logo" },
    { id: 5, logo: TableauSvgrepoLogo, alt: "TableauSvgrepo-logo" },
    { id: 6, logo: LookerSvgrepoLogo, alt: "LookerSvgrepo-logo" },
    { id: 7, logo: QlikLogo, alt: "Qlik-logo" },
    { id: 8, logo: PowerLogo, alt: "Power-logo" },
  ],
  [
    { id: 1, logo: TensorFlowLogo, alt: "TensorFlow-logo" },
    { id: 2, logo: PytorchLogo, alt: "Pytorch-logo" },
    { id: 3, logo: AzureLogo, alt: "AzureLogo-logo" },
    { id: 4, logo: OpenAiLogo, alt: "OpenAi-logo" },
    { id: 5, logo: NLTKLogo, alt: "NLTK-logo" },
    { id: 6, logo: SpaCyLogo, alt: "SpaCy-logo" },
    { id: 7, logo: GoogleAiLogo, alt: "GoogleAi-logo" },
    { id: 8, logo: HuggingFaceLogo, alt: "HuggingFace-logo" },
    { id: 9, logo: AmazonSageMakerLogo, alt: "AmazonSageMaker-logo" },
    { id: 10, logo: XGBoostLogo, alt: "XGBoost-logo" },
    { id: 11, logo: KerasLogo, alt: "Keras-logo" },
    { id: 12, logo: SLearnLogo, alt: "S-Learn-logo" },
  ],
];

export const servicesData = [
  {
    id: 1,
    title: "IT Services & Resources",
    description:
      "Connect with top-tier IT professionals, including developers, system admins, and support specialists, tailored to your project needs. Flexible options for both short and long-term engagements.",
    imageSrc: IconsServicesLogo,
    imageAlt: "IT Services Logo",
    buttonLabel: "Learn More",
  },
  {
    id: 2,
    title: "Analytics & AI Offerings",
    description:
      "Explore data-driven solutions with cutting-edge analytics and AI technologies to boost your business decision-making process.",
    imageSrc: AnalyticsLogo,
    imageAlt: "AI Illustration",
    buttonLabel: "Learn More",
  },
  {
    id: 3,
    title: "Digital Transformation",
    description:
      "Accelerate your business with end-to-end digital transformation services, helping you enhance your operational efficiency.",
    imageSrc: DigitalLogo,
    imageAlt: "Digital Transformation Image",
    buttonLabel: "Learn More",
  },
  {
    id: 4,
    title: "Tech Consultation",
    description:
      "Get expert insights from seasoned consultants on navigating the latest tech trends and optimizing your IT infrastructure.",
    imageSrc: TechLogo,
    imageAlt: "Tech Consultation Image",
    buttonLabel: "Learn More",
  },
];

export const whyUsData = [
  {
    id: 1,
    logo: globeIcon,
    title: "Vast pool of Resources",
    description:
      "Access a diverse network of qualified professionals and reliable vendors tailored to meet your project demands.",
    stroke: true,
  },
  {
    id: 2,
    logo: SettingIcon,
    title: "Streamlined  Process",
    description:
      "Manage everything from searching and interviewing to onboarding and performance tracking on a single platform.",
    stroke: false,
  },
  {
    id: 3,
    logo: toolIcon,
    title: "One-Stop Solution",
    description:
      "Whether you need IT specialists, marketing experts, or project managers, we have the right match for you, supporting your projects from start to finish.",
    stroke: true,
  },
  {
    id: 4,
    logo: rocketIcon,
    title: "Efficiency at Speed",
    description:
      "Accelerate your hiring process and secure the right talent swiftly, allowing you to focus on driving your projects to success.",
    stroke: true,
  },
  {
    id: 5,
    logo: MoneyBagIcon,
    title: "Competitive Pricing",
    description:
      "Enjoy competitive pricing models that suit your budget, offering the best value without compromising on quality.",
    stroke: false,
  },
  {
    id: 6,
    logo: EarthWithStandIcon,
    title: "Global Resources",
    description:
      "Connect with professionals from around the world, giving you the flexibility to find the perfect match for your project needs.",
    stroke: false,
  },
  {
    id: 7,
    logo: PointerArrow,
    title: "User-Friendly Experience",
    description:
      "Navigate our intuitive platform with ease, filtering based on your specific requirements and managing engagements seamlessly.",
    stroke: false,
  },
];

export const testimonials = [
  {
    image: ClientImg, // Replace with actual image import or path
    feedback:
      "HireQED made finding the right talent effortless. Their platform connected us with top professionals in no time, allowing us to focus on delivering results.",
    name: "John S.",
    position: "Project Manager at Tech Innovators",
  },
  {
    image: ClientImg,
    feedback:
      "The experience with HireQED was seamless and professional. We found candidates that exceeded our expectations.",
    name: "Emily R.",
    position: "HR Lead at Solutions Co.",
  },
  {
    image: ClientImg,
    feedback:
      "An excellent platform for recruitment. The team was supportive, and the results were outstanding.",
    name: "Michael B.",
    position: "CEO of StartupX",
  },
];

export const socialMediaData = [
  {
    id: 1,
    link: "/",
    logo: FacebookIcon,
  },
  {
    id: 2,
    link: "/",
    logo: TwitterIcon,
  },
  {
    id: 3,
    link: "/",
    logo: InstagramIcon,
  },
  {
    id: 4,
    link: "/",
    logo: LinkdinIcon,
  },
  {
    id: 5,
    link: "/",
    logo: YoutubeIcon,
  },
];
