import type { Metadata } from "next";
import "./globals.css";
import { Footer, Header } from "@/components";
import { Poppins, Source_Sans_3 } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const poppins = Poppins({
  subsets: ["latin"], // Include the subset you need
  weight: ["400", "500", "600", "700"], // Specify the font weights you want to use
  variable: "--font-poppins", // Define a CSS variable for the font
});

const Source = Source_Sans_3({
  subsets: ["latin"], // Include the subset you need
  weight: ["400", "500", "600", "700"], // Specify the font weights you want to use
  variable: "--font-sourceSans", // Define a CSS variable for the font
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${Source.variable} font-poppins  font-sans`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
